/* Run with Node and Playwright installed. Exercises the actual bundled card. */
const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const page=await browser.newPage({viewport:{width:1200,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setContent('<phantom-chess-card></phantom-chess-card>');
 const loading=page.addScriptTag({type:'module',path:path.resolve('custom_components/phantom_chess/www/phantom-chess-card.js')});
 await page.waitForTimeout(50);
 assert.equal(await page.evaluate(()=>!!customElements.get('phantom-chess-card')),false);
 await page.evaluate(()=>customElements.define('home-assistant',class extends HTMLElement {}));
 await loading;
 await page.evaluate(()=>{
  window.calls=[];window.card=document.querySelector('phantom-chess-card');
  window.config={entity:'sensor.board',connected:'binary_sensor.connected',paused:'switch.paused',voice:'switch.voice',training:'switch.training',level:'select.level',color:'select.color',view:'play'};
  window.attrs={entry_id:'board-one',full_fen:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',physical_operation:'idle',local_game_active:false,saved_games:[]};
  window.hass={states:{'sensor.board':{state:attrs.full_fen,attributes:attrs},'binary_sensor.connected':{state:'on'},'switch.training':{state:'off',attributes:{}},'select.level':{state:'3',attributes:{options:['1','2','3']}},'select.color':{state:'white',attributes:{options:['white','black']}}},callWS:async c=>{calls.push(c);if(c.service_data.action==='review') return {response:window.report||{status:'not_started',analyzed:0,total:0,moves:[],evaluations:[]}};return {response:{game_id:'g1',positions:[attrs.full_fen],sans:[],pgn:'*'}};}};
  card.setConfig(config);card.hass=hass;
 });
 await page.getByText('Choose a game',{exact:true}).click();
 assert.equal(await page.locator('[data-select="level"] option:checked').textContent(),'Level 3 · ≈1,500–1,600 benchmark Elo');
 await page.locator('[data-select="level"]').selectOption('2');
 assert.equal(await page.evaluate(()=>calls.at(-1).service_data.option),'2');
 await page.evaluate(()=>{calls.length=0;});
 await page.getByRole('button',{name:'Play my usual game',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls[0].service),'start_local_game');
 assert.equal(await page.evaluate(()=>calls[0].service_data.entry_id),'board-one');
 await page.evaluate(()=>{Object.assign(attrs,{local_game_active:true,our_color:'white',side_to_move:'white',legal_moves:['e2e4']});card.hass=hass;});
 await page.getByRole('button',{name:'e2, white pawn',exact:true}).click();
 await page.getByRole('button',{name:'e4, empty',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.at(-1).service_data.move),'e2e4');
 // Take back on your turn undoes your move and the computer's reply together.
 await page.evaluate(()=>{Object.assign(attrs,{move_history_moves:[{san:'e4',uci:'e2e4',side:'white',move_num:1},{san:'e5',uci:'e7e5',side:'black',move_num:1}]});card.hass=hass;});
 await page.getByRole('button',{name:'Take back',exact:true}).click();
 assert.deepEqual(await page.evaluate(()=>calls.at(-1).service_data),{entry_id:'board-one',count:2});
 await page.evaluate(()=>{Object.assign(attrs,{side_to_move:'black'});card.hass=hass;});
 await page.getByRole('button',{name:'Take back',exact:true}).click();
 assert.deepEqual(await page.evaluate(()=>calls.at(-1).service_data),{entry_id:'board-one'});
 await page.evaluate(()=>{Object.assign(attrs,{side_to_move:'white',move_history_moves:[]});card.hass=hass;});
 await page.evaluate(()=>{attrs.physical_operation='moving';card.hass=hass;});
 assert.equal(await page.getByRole('button',{name:'e2, white pawn',exact:true}).isDisabled(),true);
 await page.evaluate(()=>{attrs.physical_operation='idle';attrs.local_game_active=false;card.setConfig({...config,view:'review'});attrs.saved_games=[{game_id:'g1',white:'<img src=x onerror=alert(1)>',black:'Computer',status:'paused',plies:0,result:'*',updated:'2026-09-05T00:00:00Z'}];card.hass=hass;});
 assert.equal(await page.locator('phantom-chess-card img').count(),0);
 await page.locator('[data-game]').click();
 assert.equal(await page.evaluate(()=>calls.at(-1).return_response),true);
 await page.getByRole('button',{name:'Analyze game',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.some(c=>c.service_data.action==='analyze')),true);
 await page.evaluate(()=>{window.report={status:'complete',analyzed:1,total:1,moves:[{ply:1,move_num:1,side:'white',san:'f3',label:'Blunder',classification:'blunder',coaching:'Compare e4 and the suggested continuation.',before:'+0.0',after:'-4.0',variation:['e4','e5']}],evaluations:[]};card.reviewGame.positions.push(attrs.full_fen);card.reviewGame.sans.push('f3');});
 await page.evaluate(()=>card.fetchReview());
 await page.locator('[data-review-ply="1"]').click();
 assert.equal(await page.getByText('Compare e4 and the suggested continuation.',{exact:true}).count(),1);
 assert.equal(await page.getByText('Suggested line: e4 e5',{exact:true}).count(),1);
 fs.mkdirSync('docs/ui-preview',{recursive:true});
 await page.screenshot({path:'docs/ui-preview/review-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=390),true);
 await page.screenshot({path:'docs/ui-preview/review-mobile.png',fullPage:true});
 await page.setViewportSize({width:1200,height:900});
 await page.getByRole('button',{name:'Practice before this move',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.find(c=>c.service_data.action==='practice').service_data.ply),0);
 await page.getByLabel('Search games').fill('computer');
 assert.equal(await page.getByLabel('Search games').inputValue(),'computer');
 await page.evaluate(()=>{card.setConfig({...config,view:'learn'});attrs.best_move_san='e4';card.hass=hass;});
 assert.equal(await page.getByText('Coaching is off',{exact:true}).count(),2);
 await page.getByLabel('Show advantage bar').check();
 assert.equal(await page.getByRole('status').filter({hasText:'Evaluation pending'}).count(),1);
 await page.evaluate(()=>{Object.assign(attrs,{eval_cp:100,eval_fen:attrs.full_fen,eval_depth:18});card.hass=hass;});
 assert.equal(await page.getByRole('img',{name:'White advantage, +1.0'}).count(),1);
 await page.evaluate(()=>{attrs.eval_fen='stale';card.hass=hass;});
 assert.equal(await page.getByRole('img').count(),0);
 await page.evaluate(()=>{Object.assign(attrs,{eval_fen:attrs.full_fen,eval_mate:-3});card.hass=hass;});
 assert.equal(await page.getByRole('img',{name:'Black advantage, Mate 3'}).count(),1);
 await page.evaluate(()=>{attrs.eval_mate=0;card.hass=hass;});
 assert.equal(await page.getByRole('img').count(),0);
 await page.evaluate(()=>{attrs.lichess_active=true;card.hass=hass;});
 assert.equal(await page.getByRole('img').count(),0);
 await page.evaluate(()=>{attrs.lichess_active=false;hass.states['switch.training'].state='on';attrs.move_history_moves=[{san:'Qh5',classification:'blunder',best_san:'Nf3'},{san:'e5',classification:'unknown'}];card.hass=hass;});
 assert.equal(await page.getByLabel('Blunder',{exact:true}).count(),1);
 assert.equal(await page.getByText('Not analyzed',{exact:false}).count(),1);
 await page.getByLabel('Show advantage bar').uncheck();
 assert.equal(await page.getByRole('img').count(),0);
 await page.evaluate(()=>{hass.states['switch.training'].state='off';card.hass=hass;});
 assert.equal(await page.getByLabel('Move coaching').count(),0);
 await page.evaluate(()=>{card.setConfig({...config,view:'settings'});attrs.engine_health={status:'error',error:'Engine download is incomplete'};card.hass=hass;});
 assert.equal(await page.getByText('Engine download is incomplete',{exact:true}).count(),1);
 await page.getByRole('button',{name:'Check chess engine',exact:true}).click();
 assert.equal(await page.evaluate(()=>calls.at(-1).service),'check_engine');
 await page.evaluate(()=>{attrs.local_game_active=true;card.hass=hass;});
 assert.equal(await page.getByRole('button',{name:'Check chess engine',exact:true}).isDisabled(),true);
 await page.evaluate(()=>{attrs.local_game_active=false;card.hass=hass;});
 await page.evaluate(()=>{card.setConfig({...config,view:'play'});attrs.engine_error='Engine unavailable';card.hass=hass;});
 assert.equal(await page.getByRole('alert').filter({hasText:'Engine unavailable'}).count(),1);
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=390),true);
 await page.evaluate(()=>{Object.assign(attrs,{game_status:'checkmate',side_to_move:'white',local_game_active:false});card.hass=hass;});
 assert.equal(await page.getByRole('heading',{name:'Checkmate — Black wins',exact:true}).count(),1);
 assert.equal(await page.getByText('White is in check with no legal escape. No further moves can be played.',{exact:true}).count(),1);
 assert.equal(await page.getByRole('link',{name:'Open game review →',exact:true}).count(),1);
 await page.evaluate(()=>{attrs.side_to_move='black';card.hass=hass;});
 assert.equal(await page.getByRole('heading',{name:'Checkmate — White wins',exact:true}).count(),1);
 await page.evaluate(()=>{attrs.game_status='stalemate';card.hass=hass;});
 assert.equal(await page.getByRole('heading',{name:'Draw — stalemate',exact:true}).count(),1);
 await page.evaluate(()=>{attrs.game_status='draw';card.hass=hass;});
 assert.equal(await page.getByRole('heading',{name:'Game drawn',exact:true}).count(),1);
 await page.evaluate(()=>{attrs.game_status='check';attrs.local_game_active=true;card.hass=hass;});
 assert.equal(await page.getByRole('heading',{name:'Black is in check',exact:true}).count(),1);
 await page.evaluate(()=>{attrs.game_status='idle';attrs.local_game_active=false;card.hass=hass;});
 fs.mkdirSync('docs/ui-preview',{recursive:true});
 await page.screenshot({path:'docs/ui-preview/mobile.png',fullPage:true});
 await page.setViewportSize({width:1200,height:900});
 await page.evaluate(()=>{attrs.engine_error=null;card.hass=hass;});
 await page.screenshot({path:'docs/ui-preview/desktop.png',fullPage:true});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Frontend: 39 behavioral assertions passed; desktop and mobile rendered.');
})().catch(e=>{console.error(e);process.exitCode=1;});
